name: owlenome
description: Owlenome - Owl&#x27;s metronome

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  provider: ^4.1.1
  wheel_chooser: ^0.1.0
  flutter_xlider: ^3.4.0
  device_preview: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Portrait background
    - images/BackgV.jpg
    # Landscape background
    - images/BackgH.jpg
    - images/Backg-Up-1.jpg
    - images/Backg-Dn-1.jpg
    - images/Backg-Up-1.png
    - images/Backg-Dn-1.png
    - images/TempoKnob.png
    - images/TempoKnobT.png
    - images/owl-sub.png
    - images/owl-btn.png
    - images/Metre.png

    - images/owl3-0-0.png
    - images/owl3-0-1.png
    - images/owl3-1-0.png
    - images/owl3-1-1.png
    - images/owl3-1-2.png
    - images/owl3-1-3.png
    - images/owl3-1-4.png
    - images/owl3-2-0.png
    - images/owl3-2-1.png
    - images/owl3-2-2.png
    - images/owl3-2-3.png
    - images/owl3-2-4.png
    - images/owl3-3-0.png
    - images/owl3-3-1.png
    - images/owl3-3-2.png
    - images/owl3-3-3.png
    - images/owl3-3-4.png
    - images/owl3-4-0.png
    - images/owl3-4-1.png
    - images/owl3-4-2.png
    - images/owl3-4-3.png
    - images/owl3-4-4.png

    - images/owl5-0-0.png
    - images/owl5-0-1.png
    - images/owl5-1-0.png
    - images/owl5-1-1.png
    - images/owl5-1-2.png
    - images/owl5-1-3.png
    - images/owl5-1-4.png
    - images/owl5-2-0.png
    - images/owl5-2-1.png
    - images/owl5-2-2.png
    - images/owl5-2-3.png
    - images/owl5-2-4.png
    - images/owl5-3-0.png
    - images/owl5-3-1.png
    - images/owl5-3-2.png
    - images/owl5-3-3.png
    - images/owl5-3-4.png
    - images/owl5-4-0.png
    - images/owl5-4-1.png
    - images/owl5-4-2.png
    - images/owl5-4-3.png
    - images/owl5-4-4.png

    - images/owl6-1.png
    - images/owl6-2.png
    - images/owl6-3.png
    - images/owl6-4.png
    - images/owl6h-0-0.png
    - images/owl6h-0-1.png
    - images/owl6h-1-0.png
    - images/owl6h-1-1.png

    - images/sound0.png
    - images/sound1.png
    - images/sound2.png
    - images/sound3.png
    - images/help.jpg
    - images/Ad-1.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
